name = "cloudflare-poem-next"
compatibility_date = "2024-08-06"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[kv_namespaces]]
binding = "KV"
id = "f1c144608d9c4a1991c98a966e800934"

[[r2_buckets]]
binding = 'BUCKET'
bucket_name = 'cloudflare-poem-bucket'
